# Generated by Django 3.2 on 2021-12-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211224_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='activation_key_expires',
            new_name='activation_key_expired',
        ),
    ]
